# Generated by Django 2.0.5 on 2022-03-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_kyc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=300)),
                ('cname', models.CharField(max_length=300)),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('aadhar', models.FileField(upload_to='')),
                ('voter_id', models.FileField(upload_to='')),
                ('pan_card', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=300)),
            ],
        ),
    ]
