# Generated by Django 2.0.5 on 2022-03-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_upload_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_kyc',
            name='banklocation',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload_kyc',
            name='bankname',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
