# Generated by Django 2.0.5 on 2022-03-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220314_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_kycdet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=300)),
                ('cname', models.CharField(max_length=300)),
                ('aadhar', models.FileField(upload_to='')),
                ('voter_id', models.FileField(upload_to='')),
                ('pan_card', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=300)),
                ('bankname', models.CharField(max_length=300)),
                ('banklocation', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='upload_kyc',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='upload_kyc',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='upload_kyc',
            name='status',
        ),
        migrations.RemoveField(
            model_name='upload_kyc',
            name='voter_id',
        ),
    ]
