# Generated by Django 2.0.5 on 2022-03-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20220315_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='sharekey_request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=300)),
                ('cname', models.CharField(max_length=300)),
                ('bankid', models.CharField(max_length=300)),
                ('bankname', models.CharField(max_length=300)),
                ('buname', models.CharField(max_length=300)),
                ('bemail', models.CharField(max_length=300)),
                ('hashvalue', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
            ],
        ),
    ]
