# Generated by Django 2.0.5 on 2022-03-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_sharekey_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='pkey_request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=300)),
                ('cname', models.CharField(max_length=300)),
                ('bankid', models.CharField(max_length=300)),
                ('bankname', models.CharField(max_length=300)),
                ('buname', models.CharField(max_length=300)),
                ('bemail', models.CharField(max_length=300)),
                ('pkey1', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
            ],
        ),
    ]
